import os
import glob
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

def main():
    # Find all CSV files generated by the retrieval benchmark
    csv_files = glob.glob('results/retrieval_*.csv')
    
    if not csv_files:
        print("No CSV files found in 'results/'. Run the benchmark first.")
        return
        
    os.makedirs('plots', exist_ok=True)
    sns.set_theme(style="darkgrid", palette="muted")
    
    # We will aggregate learning curves 
    # model -> seq_len -> dataframe
    data_dict = {}
    
    for f in csv_files:
        basename = os.path.basename(f)
        # Format: retrieval_{model}_{seq_len}.csv
        parts = basename.replace('.csv', '').split('_')
        if len(parts) >= 3:
            model = parts[1]
            seq_len = int(parts[2])
            
            if model not in data_dict:
                data_dict[model] = {}
            data_dict[model][seq_len] = pd.read_csv(f)
            
    # Plot 1: Learning curves for a specific sequence length across all models
    # Find all unique sequence lengths
    all_seq_lens = set()
    for m in data_dict:
        all_seq_lens.update(data_dict[m].keys())
        
    for seq_len in sorted(list(all_seq_lens)):
        plt.figure(figsize=(10, 6))
        
        for model in data_dict:
            if seq_len in data_dict[model]:
                df = data_dict[model][seq_len]
                plt.plot(df['epoch'], df['test_acc'], label=f"{model}", marker='o', linewidth=2)
                
        plt.title(f'Associative Retrieval Test Accuracy (Sequence Length: {seq_len})', fontsize=14)
        plt.xlabel('Epoch', fontsize=12)
        plt.ylabel('Test Accuracy', fontsize=12)
        plt.ylim(0, 1.05)
        plt.legend(fontsize=12)
        plt.grid(True, alpha=0.3)
        plt.tight_layout()
        
        plot_path = f'plots/retrieval_acc_seq_{seq_len}.png'
        plt.savefig(plot_path, dpi=300)
        print(f"Saved plot to {plot_path}")
        plt.close()

if __name__ == "__main__":
    main()
